"""Add Social ID Login DB Schema

Revision ID: 09eb3f5049ad
Revises: e0cbbfb1ba29
Create Date: 2026-07-05 12:05:44.464560

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "09eb3f5049ad"
down_revision: str | Sequence[str] | None = "e0cbbfb1ba29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('login_type', sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'), nullable=True, default=None))
    # op.add_column('users', sa.Column('social_id', sa.String(), nullable=True))
    # op.alter_column('users', 'password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'password',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.drop_column('users', 'social_id')
    # op.drop_column('users', 'login_type')
    pass
    #  ### end Alembic commands ###
