"""remove user_id

Revision ID: 0f7ea4890a5f
Revises: 60aa9e7a727e
Create Date: 2026-07-11 20:45:58.345462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f7ea4890a5f'
down_revision: Union[str, Sequence[str], None] = '60aa9e7a727e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payment_transactions_user_id_fkey'), 'payment_transactions', type_='foreignkey')
    op.drop_column('payment_transactions', 'user_id')
    # op.alter_column('users', 'login_type',
    #            existing_type=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            type_=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'login_type',
    #            existing_type=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            type_=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            nullable=False)
    op.add_column('payment_transactions', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('payment_transactions_user_id_fkey'), 'payment_transactions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
