"""Updt: Add Role Table

Revision ID: 11f325940cbf
Revises: 35a9e46fdd02
Create Date: 2026-07-03 14:26:42.341892

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "11f325940cbf"
down_revision: str | Sequence[str] | None = "35a9e46fdd02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
