"""Add otp, otp_expiry column to User Table

Revision ID: 35a9e46fdd02
Revises: f9366b160601
Create Date: 2026-07-03 12:13:38.659433

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35a9e46fdd02"
down_revision: str | Sequence[str] | None = "f9366b160601"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("otp", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("otp_expiry", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "otp_expiry")
    op.drop_column("users", "otp")
    # ### end Alembic commands ###
