"""Add Subscription and Invoice Table

Revision ID: 819d811ae273
Revises: 2543b3529f4d
Create Date: 2026-07-14 12:23:14.972331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '819d811ae273'
down_revision: Union[str, Sequence[str], None] = '2543b3529f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='created', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=True),
    sa.Column('cancel_at_cycle_end', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('current_period_start', sa.BigInteger(), nullable=True),
    sa.Column('current_period_end', sa.BigInteger(), nullable=True),
    sa.Column('ended_at', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('razorpay_invoice_id', sa.String(length=255), nullable=False),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_start', sa.BigInteger(), nullable=True),
    sa.Column('billing_end', sa.BigInteger(), nullable=True),
    sa.Column('paid_at', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_invoice_id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    # op.alter_column('users', 'login_type',
    #            existing_type=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            type_=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'login_type',
    #            existing_type=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            type_=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            nullable=False)
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
