"""Add Refresh Token Field

Revision ID: 865039e44277
Revises: f5196a14523b
Create Date: 2026-07-07 14:05:23.445348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '865039e44277'
down_revision: Union[str, Sequence[str], None] = 'f5196a14523b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('refresh_token', sa.String(), nullable=True))
    op.alter_column('user_sessions', 'session',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # op.alter_column('users', 'login_type',
    #            existing_type=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            type_=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'login_type',
    #            existing_type=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            type_=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            nullable=False)
    op.alter_column('user_sessions', 'session',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_sessions', 'refresh_token')
    # ### end Alembic commands ###
