"""Add CallRoom table

Revision ID: 87b089922c11
Revises: 865039e44277
Create Date: 2026-07-09 10:30:26.104919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87b089922c11'
down_revision: Union[str, Sequence[str], None] = '865039e44277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_rooms',
    sa.Column('room_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('host_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_rooms_id'), 'call_rooms', ['id'], unique=False)
    op.create_index(op.f('ix_call_rooms_room_code'), 'call_rooms', ['room_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_rooms_room_code'), table_name='call_rooms')
    op.drop_index(op.f('ix_call_rooms_id'), table_name='call_rooms')
    op.drop_table('call_rooms')
    # ### end Alembic commands ###
