"""Add Forgot Password Table

Revision ID: 9ff363583ee2
Revises: b9faf52e4e22
Create Date: 2026-07-07 12:12:56.783438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ff363583ee2'
down_revision: Union[str, Sequence[str], None] = 'b9faf52e4e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'login_type',
    #            existing_type=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            type_=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'login_type',
    #            existing_type=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            type_=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            nullable=False)
    pass
    # ### end Alembic commands ###
