"""Add razorpay_item_id

Revision ID: da1027f3e977
Revises: 1b3432735d98
Create Date: 2026-07-13 17:13:24.362244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da1027f3e977'
down_revision: Union[str, Sequence[str], None] = '1b3432735d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('razorpay_item_id', sa.String(), nullable=True))
    op.drop_column('subscription_plans', 'is_recuring')
    # op.alter_column('users', 'login_type',
    #            existing_type=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            type_=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_type',
               existing_type=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
               type_=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
               nullable=False)
    op.add_column('subscription_plans', sa.Column('is_recuring', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('subscription_plans', 'razorpay_item_id')
    # ### end Alembic commands ###
