"""Update role_id's constraits

Revision ID: e0cbbfb1ba29
Revises: 445ea7bcb84a
Create Date: 2026-07-03 14:30:09.703839

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0cbbfb1ba29"
down_revision: str | Sequence[str] | None = "445ea7bcb84a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
