"""Add Forgot Password Table 2

Revision ID: f5196a14523b
Revises: 9ff363583ee2
Create Date: 2026-07-07 12:16:33.521046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5196a14523b'
down_revision: Union[str, Sequence[str], None] = '9ff363583ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_forgot_password_track',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('link_expiry', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_forgot_password_track_id'), 'user_forgot_password_track', ['id'], unique=False)
    # op.alter_column('users', 'login_type',
    #            existing_type=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            type_=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'login_type',
    #            existing_type=sa.Enum('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='logintype'),
    #            type_=postgresql.ENUM('EMAIL', 'GOOGLE', 'GITHUB', 'FACEBOOK', name='login_type_enum'),
    #            nullable=False)
    op.drop_index(op.f('ix_user_forgot_password_track_id'), table_name='user_forgot_password_track')
    op.drop_table('user_forgot_password_track')
    # ### end Alembic commands ###
